### ISSUE TITLE
webpack-cli (v5.1.4) doesn't work with tsx(v4.14.0) for webpack.config.ts

### ISSUE THREAD

**Issue by Dmitriy-Frostoff** [privatenumber/tsx#584]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/Dmitriy-Frostoff/boilerplate-webpack-gulp-html-scss-ts-components

### What were you expecting to happen?

I expected to get the bundle (developmaent, production ones).

### What actually happened?

I got errors in the terminal output.

### Terminal output / screenshots

```bash
$ npm run dev

> boilerplate-webpack-gulp-html-scss-ts-components@1.0.0 dev
> cross-env NODE_OPTIONS='--import=tsx' TSX_TSCONFIG_PATH='./configs/ts/tsconfig.json' webpack --config ./configs/webpack/webpack.co
nfig.ts --node-env=development --progress

[webpack-cli] Unable load 'E:\Code learning\boilerplate-webpack-gulp-html-scss-ts-components\configs\webpack\webpack.config.ts'
[webpack-cli] Unable to use specified module loaders for ".ts".
[webpack-cli] Cannot find module 'ts-node/register' from 'E:\Code learning\boilerplate-webpack-gulp-html-scss-ts-components\configs\
webpack'
[webpack-cli] Cannot find module 'sucrase/register/ts' from 'E:\Code learning\boilerplate-webpack-gulp-html-scss-ts-components\confi
gs\webpack'
[webpack-cli] Cannot find module '@babel/register' from 'E:\Code learning\boilerplate-webpack-gulp-html-scss-ts-components\configs\w
ebpack'
[webpack-cli] Cannot find module 'esbuild-register/dist/node' from 'E:\Code learning\boilerplate-webpack-gulp-html-scss-ts-component
s\configs\webpack'
[webpack-cli] Cannot find module '@swc/register' from 'E:\Code learning\boilerplate-webpack-gulp-html-scss-ts-components\configs\webpack'
[webpack-cli] Please install one of them

```

### Please provide the following information:

OS & version [e.g. MacOS Catalina 10.15.4]: Windows 10 Pro v1803 (i.e. Windows 10 v10.0.17134)
node version (run node -v): v21.7.1
npm version (run npm -v): 10.8.1
webpack-cli version (run npx webpack -v): 5.1.4
tsx version (run npx tsx -v): 4.14.0

(more details via `package.json` s at
[boilerplate-webpack-gulp-html-scss-ts-components](https://github.com/Dmitriy-Frostoff/boilerplate-webpack-gulp-html-scss-ts-components)  
I use ESM and "type": "module", in the package.json
)

### Steps to reproduce:

- copy the [boilerplate](https://github.com/Dmitriy-Frostoff/boilerplate-webpack-gulp-html-scss-ts-components)
- install the dependencies
- check out that the command

```bash
npm run dev
```

works fine;

- update `tsx`to actual version

- run

```bash
npm run dev
```

or

```bash
npm run build
```

### Additional information

The exceptions are emitted only via actual `tsx` v4.14.0 usage, previous one (v4.12.0) works fine.  
I hope it'll help to find the problem...
If there's any additional info required I'll immediately provide it!))
Sorry 🙏 for more than 200 words, but I hope it worth it...
Thanks! `tsx` is marvelous tool!!!))

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Thanks for the issue @Dmitriy-Frostoff 

Please provide a _minimal_ reproduction next time as it puts work on me to debug an unnecessarily large codebase.

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.14.1

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:

**Comment by Dmitriy-Frostoff** [comment]
Dear Hiroki Osame,
Thank you so much for your kindness and understanding. I sincerely apologize for the extensive code in my previous report that required more of your time to dig through. I've clearly understood the importance of providing only the relevant code to reproduce the issue and narrow down the testing scope. I will ensure to do so in future contributions!)))) 🙏🙏🙏🙏
Best regards,
Dmitriy Frostoff
