### ISSUE TITLE
ERR_MODULE_NOT_FOUND when importing without .js since v4.14.0

### ISSUE THREAD

**Issue by lukaswiklund** [privatenumber/tsx#585]
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [x] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/edit/node-arpgm8

### Problem & expected behavior (under 200 words)

Since v1.14.0 when using the TS config option "allowImportingTsExtensions: true" I cannot import the UTC extension of Dayjs without using the .js extension. This works when downgrading to v4.13. The Stackbliz editor gives an error either way but that's not relevant here.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by matt-blanchette** [comment]
Seeing the same with `import 'source-map-support/register';`
Returning the same error starting in 4.14.0: 
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../node_modules/source-map-support/register' imported from __.ts
Did you mean to import "source-map-support/register.js"?
```

**Comment by U-4-E-A** [comment]
Same issue with importing `.ts` files from a package in my repo. Not working in `v4.15.1`, working when reverted back to `v4.13.2`. `mypackage\src\MyFile` below is `mypackage\src\MyFile.ts`: - 

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<redacted>@repo\mypackage\src\MyFile' imported from '<redacted>\packages\public\src\server.ts
```

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.15.2

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:
